### ISSUE TITLE
Editing files has become buggy, not saving changes and garbage added to the end of files on save.

### ISSUE THREAD

**Issue by ioogithub** [billthefarmer/editor#134] opened 2021-06-13 19:23 UTC
Two issues I have encountered recently:

**Edits are not being saved**
1. Press the edit icon
2. make a small change
3. press the save icon
4. open the file again, the change was not made.
5. repeat 1-4 and observe the same problem.

This is intermittent and I cannot reproduce it every time however when I notice it once, I can always try to make successive edits and it will always fail for this particular file.

**Garbage is being saved at the bottom of the text files.**
I have noticed this around half a dozen times now. I will make several edits to a script then the script fails. It took me a while to figure out what was going on. I finally realized that garbage is being saved at the bottom of the text file, it appears to be fragments of text lines from the earlier in the file. This is also intermittent and I cannot reproduce it every time. It seems like an issue with a buffer when the file is saved some extra text is written at the end of the file.

I had to stop using editor because of these two issues, I believe there are related.

Version: 1.56 (f-droid version)
System: LineageOS 17.1

**Comment by billthefarmer** [comment] 2021-06-14 08:59
I can't reproduce that, I'm also using LineageOS 17.1. I need a bit more information &ndash; Where are the files stored? A copy of a corrupted file.

**Comment by ioogithub** [comment] 2021-06-14 22:12
I have been using your app for around a year mainly due to the word wrap toggle support which is very nice to editing scripts with indentation. I only started noticing it in the last week. I had one file yesterday where I could do this:

1. Open
2. Click pencil icon
3. make a change
4. click save icon
5. close file
6. open file again - change not made.

I repeated this 4 or 5 times.

When I edit that file again today and make a change it works so it isn't happening all the time.

Regarding the junk at the end of the file issue, I have seen this several times this week as well but I can't produce it again right now either.

The files are scripts in various places in /data/data so ext4. I will post again when I see it again.

**Comment by billthefarmer** [comment] 2021-06-15 12:02
`/data/data` appears to be [apps specific data area](https://developer.android.com/training/data-storage/app-specific) which you shouldn't be able to access from an ordinary app like Editor. It's possible that some apps have processes running in the background that access these files believing that access is exclusive have made changes that clash with changes Editor has made. Editor attempts to detect this by comparing modification dates, but it's not guaranteed.

**Comment by ioogithub** [comment] 2021-07-01 18:32
> `/data/data` appears to be [apps specific data area](https://developer.android.com/training/data-storage/app-specific) which you shouldn't be able to access from an ordinary app like Editor.

Yes I understand that however user scripts are in /data/data/com.termux/files/home/.shortcuts which is the main reason to need a text editor with the comprehensive features yours offers. I do not believe any other apps are accessing these script files as they are not running so I don't think that is the issue. It seems more like a buffer issue as I always detect a few duplicated lines at the bottom of the file. The other issue is that intermittently I will enter the edit mode make a change and it will not save, most of the time it does but sometimes it does not.

I can use the app to view these files because you have implemented Word wrap which is essential for scripts and file with indentation however I cannot use it to edit file any longer due to the issue I mentioned. If this is an issue that will not be investigated, do you know of any other OSS editor apps that have implemented word wrap and the other excellent features you are offering?

**Comment by billthefarmer** [comment] 2021-07-02 10:50
As I have said in response to @jaimet [here](https://github.com/billthefarmer/editor/issues/138#issuecomment-872526797), the code for saving files in this app is extremely simple and delegates this to the android Java library. I haven't tested other android text editors, but they are likely to be using exactly the same or similar code for saving files, so may have similar problems.

**Comment by ioogithub** [comment] 2021-07-02 16:13
None of the other text editors I have tried exhibit this issue, it is very specific to this app. I see it all the time and have never seen it with others. The others however lack the nice features of your app so if the issue won't be addressed I will continue using it as a read only text app and look for alternatives.

**Comment by ioogithub** [comment] 2021-07-02 16:20
I should also note that I have seen the issue on two different devices and two different operating systems (Android 10 and Android 11)

**Comment by billthefarmer** [comment] 2021-07-02 16:40
I can't address the issue until someone comes up with a clue as to what is causing it.

**Comment by billthefarmer** [comment] 2021-07-13 08:30
I have found a 'fix' which will be in the next version.

**Comment by ioogithub** [comment] 2021-07-20 02:25
Should the issue be fixed in version 1.59? I have been testing it this week and I can confirm this issue is still present.

It seems quite specific, I can edit a script, change a few characters in the middle of the file. When it is saved and I open the file again, the change was not saved however the last 2 or 3 lines of the bottom of the file are duplicated.

It does not happen every time but maybe 20-25% of the attempted edits fail.

**Comment by billthefarmer** [comment] 2021-07-20 06:40
No, I tried something else in [1.59](https://github.com/billthefarmer/editor/releases/tag/v1.59). It should be fixed in [1.60](https://github.com/billthefarmer/editor/releases/tag/v1.60). Which has been built by  [F-Droid](https://f-droid.org/packages/org.billthefarmer.editor/) and should be available soon.

**Closed** 2021-07-23 10:14 UTC
